# Generated by Django 3.1.7 on 2021-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('phone', models.BigIntegerField(null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=20, null=True, verbose_name='邮箱')),
                ('user_img', models.ImageField(default='', upload_to='static/img/user_img')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=6)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
